export const projects = [ 
  {
    img: "heladeria.png",
    title: "Heladería Chilly Willy",
    type:"Front-End && Back-End",
    text: "Chilly Willy es una aplicación web para la gestión de una heladería, con roles de administrador, cliente y vendedor. Permite visualizar ventas, inventarios y productos en tiempo real. El backend fue desarrollado utilizando Supabase, facilitando la autenticación, base de datos y gestión de la información.",
    classN: ["React", "CSS", "TypeScript", "SupaBase"],
    view: "https://heladeria-chilly-willy.vercel.app/",
    front: "https://github.com/cristian10cm/heladeria-ChillyWilly",
  },
  {
    img: "vecii.png",
    title: "Vecii App",
    type:"Front-End",
    text: "Vecii App es una plataforma diseñada para la gestión integral de conjuntos residenciales. Cuenta con roles como administrador, guarda de seguridad y residente. En este proyecto estuve a cargo del desarrollo completo de la interfaz de usuario (UI), así como de la integración de WebSockets y APIs. Se implementaron patrones de diseño, arquitecturas escalables, dashboards interactivos y un diseño visual enfocado en la usabilidad.",
    classN: ["Next Js", "Tailwind", "TypeScript"],
  },
  {
    img: "pets-project.png",
    title: "Social Pets",
    type:"Front-End && Back-End",
    text: "Social Pets es una aplicación web donde los usuarios pueden crear perfiles para sus mascotas, publicar contenido, comentar y dar likes. Incluye autenticación con JWT y una API REST desarrollada en NestJS. El frontend está construido con Next.js y Tailwind CSS, usando Prisma ORM, Docker y TypeScript.",
    classN: ["Nestjs", "Docker", "Prisma", "Next Js", "Tailwind", "Typescript"],
    front: "https://github.com/cristian10cm/App_Mascotas",
    back: "https://github.com/cristian10cm/nest_demo_mascotas",
  },
  {
    img: "barber-style.png",
    title: "Barber Style App",
    type:"Front-End && Back-End",
    text: "Barber Style App es una app nativa que gestiona el sistema de servicios y reservación de citas de las barberías y salones de belleza de Bogotá, se desarrollo en Kotlin con Jetpack Compose y se utilizo SupaBase para el Backend .",
    classN: ["Kotlin", "SupaBase"],
    front: "https://github.com/cristian10cm/App_nativa_barberStyle/tree/main",
  },
  {
    img: "tech-shop.png",
    title: "Technology Store Bogota",
    type:"Front-End && Back-End",
    text: "Aplicación web desarrollada con NestJS y Next.js que permite a los usuarios registrarse, iniciar sesión, publicar productos tecnológicos. Implementa una API REST con Arquitectura Hexagonal, autenticación JWT, Prisma ORM, PostgreSQL y Docker para un desarrollo escalable y mantenible.",
    classN: ["Nestjs", "Docker", "Prisma", "Next Js", "Tailwind","REST API"],
    front: "https://github.com/AndresFonseca13/Proyecto_Backend_UCompensar",
    back: "https://github.com/cristian10cm/Backend_app_tec",
  },
  {
    img: "poke-app.png",
    type:"Front-End",
    title: "Poke App",
    text: "Poke App es una App hibrida donde puedes ver todos los pokemones, añadir a favoritos y agregar nuevos pokemones, se hace uso de la poke Api para obtener los diferentes pokemones ,realizada con expo y React Native.  .",
    classN: ["React native", "Typescript"],
    front: "https://github.com/cristian10cm/app_galerry_pokemon",
  },
  {
    img: "spring-project.png",
    type:"Back-End",
    title: "API of medicine Spring Boot",
    text: "API REST de gestión de medicamentos desarrollada con Spring Boot, que implementa autenticación con JWT, Spring Security, Spring Data JPA, PostgreSQL, Docker y validación mediante DTOs, ofreciendo una arquitectura robusta y escalable para operaciones CRUD seguras.",
    classN: ["Spring Boot", "JPA Hibernate", "Docker","PostgreSQL","REST API"],
    back: "https://github.com/cristian10cm/Firts_Api_springBoot",
  },
  {
    img: "shenlong.png",
    title: "Shenlong Adivina",
    type:"Front-End",
    text: "Shenlong Adivina es una aplicación inspirada en el juego 'Pedro Responde', con temática de Dragon Ball. Utilizando las esferas del dragón, el usuario puede responder cualquier pregunta y gastar bromas a sus amigos. Incluye un truco especial que permite escribir la respuesta mientras se redacta la supuesta petición, el cual se activa al hacer clic en las esferas del dragón.",
    classN: ["React", "CSS", "JavaScript"],
    view: "https://cristian10cm.github.io/Shenlong-page/",
    front: "https://github.com/cristian10cm/Shenlong-Adivina",
  },
  {
    img: "tupeli.png",
    title: "Tu Peli",
    type:"Front-End",
    text: "Tu Peli es una plataforma similar a Netflix o HBO, donde se muestra contenido multimedia de forma organizada e intuitiva. Para la obtención de la información se utiliza la API de Jikan, permitiendo consultar y visualizar datos detallados de cada contenido disponible en la aplicación.",
    classN: ["Next Js", "CSS", "TypeScript"],
    view: "https://heladeria-chilly-willy-zq1u.vercel.app/",
    front: "https://github.com/cristian10cm/tuPeli.com",
  },
   {
    img: "calculo.png",
    title: "Calculadora de costos totales y utilidades en una empresa",
    text: "Proyecto enfocado en el cálculo de costos y utilidades empresariales mediante el uso del cálculo integral. Se desarrolló una interfaz sencilla e intuitiva que permite visualizar los resultados a través de dashboards interactivos, facilitando el análisis financiero de la empresa.",
    type:"Front-End",
    classN: ["Next Js", "Tailwind", "TypeScript"],
    view: "https://calculo-integral-beige.vercel.app/",
    front: "https://github.com/cristian10cm/calculo-integral",
  },
  
 
];
